@php
    /** @var \App\Support\Documents\DocumentDefinition $document */
    $context = $document->context;
@endphp
<div class="doc-header">
    <table width="100%" cellspacing="0" cellpadding="0">
        <tr>
            <td width="58%">
                <table cellspacing="0" cellpadding="0">
                    <tr>
                        <td>
                            @if (filled($context->logoDataUri))
                                <img src="{{ $context->logoDataUri }}" alt="" class="logo">
                            @else
                                <div class="mark">{{ $context->productMark }}</div>
                            @endif
                        </td>
                        <td>
                            <div class="brand-name">{{ $context->productName }}</div>
                            <div class="agency">{{ $context->agencyName }}</div>
                        </td>
                    </tr>
                </table>
            </td>
            <td>
                <div class="doc-title">{{ $document->title }}</div>
                @if ($document->subtitle !== '')
                    <div class="doc-sub">{{ $document->subtitle }}</div>
                @endif
                @if ($document->reference !== '')
                    <div class="doc-ref">{{ $document->reference }}</div>
                @endif
            </td>
        </tr>
    </table>
</div>

@include($document->view, $document->data)

<div class="doc-footer">
    <table cellspacing="0" cellpadding="0">
        <tr>
            <td width="48%">
                Generated by: {{ $context->generatedByName }} · {{ $context->generatedByRole }}<br>
                Generated: {{ $context->generatedAtLabel }}
            </td>
            <td width="52%">
                {{ $context->confidentiality }}
            </td>
        </tr>
    </table>
</div>
@if (!empty($forPdf))
<script type="text/php">
if (isset($pdf)) {
    $pdf->page_text(510, 770, 'Page {PAGE_NUM} of {PAGE_COUNT}', $fontMetrics->get_font('DejaVu Sans', 'normal'), 8);
}
</script>
@endif
