import type { OptionItem } from '@/types/directory';

export type DemoEmployeeFill = Record<string, unknown>;

export function demoEmployeeFill(supervisors: OptionItem[]): DemoEmployeeFill {
    const stamp = Date.now().toString().slice(-5);

    return {
        first_name: 'Alex',
        middle_name: 'J',
        last_name: 'Rivera',
        employee_number: '',
        job_type: 'dsp',
        job_title: 'Direct Support Professional',
        employment_status: 'active',
        employment_type: 'full_time',
        hired_on: '2024-03-18',
        date_of_birth: '1994-06-12',
        email: `alex.rivera.${stamp}@example.com`,
        home_phone: '555-014-2201',
        cell_phone: '555-014-2298',
        alternate_phone: '',
        supervisor_id: supervisors[0] ? String(supervisors[0].id) : '',
        address_line_1: '218 Willow Street',
        address_line_2: 'Apt 4',
        city: 'Lakeside',
        state: 'OH',
        postal_code: '44001',
        previous_address_line_1: '90 Harbor Road',
        previous_city: 'Lakeside',
        previous_state: 'OH',
        previous_postal_code: '44002',
        emergency_contact_name: 'Morgan Rivera',
        emergency_contact_relationship: 'Sibling',
        emergency_contact_phone: '555-014-2210',
        how_heard: 'Current DSP referral',
        employment_interest: 'Weekday residential and community support.',
        preferred_shift_type: 'Day',
        desired_hours_per_week: '32',
        willing_long_term: true,
        willing_short_term: true,
        willing_pets: true,
        willing_smoke: false,
        availability_days: [1, 2, 3, 4, 5].map((weekday) => ({
            weekday,
            is_available: true,
            starts_at: '07:00',
            ends_at: '15:00',
            preferred_daypart: 'morning',
        })).concat(
            [6, 0].map((weekday) => ({
                weekday,
                is_available: false,
                starts_at: '07:00',
                ends_at: '15:00',
                preferred_daypart: '',
            })),
        ),
        has_drivers_license: true,
        license_state: 'OH',
        license_number: 'OH-4829103',
        vehicle_make_year: '2019 Honda Civic',
        insurance_company: 'Nationwide',
        insurance_policy_number: 'NV-204881',
        has_moving_violations: false,
        moving_violations_description: '',
        educations: [
            {
                level: 'high_school',
                institution_name: 'Lakeside High School',
                city: 'Lakeside',
                state: 'OH',
                country: 'USA',
                graduated: true,
                years_completed: '4',
                degree: 'Diploma',
            },
            {
                level: 'college',
                institution_name: 'Cuyahoga Community College',
                city: 'Cleveland',
                state: 'OH',
                country: 'USA',
                graduated: false,
                years_completed: '2',
                degree: '',
            },
        ],
        credentials: [
            {
                type: 'professional_license',
                name: 'First Aid / CPR',
                issuer: 'American Red Cross',
                credential_number: 'CPR-4419',
                expires_on: '2027-04-01',
                status: 'active',
            },
        ],
        license_ever_suspended: false,
        license_suspension_explanation: '',
        references: [
            {
                name: 'Pat Nguyen',
                address: '14 Maple Court, Lakeside, OH',
                home_phone: '555-201-1001',
                work_phone: '555-201-1100',
                relationship: 'Former supervisor',
            },
            {
                name: 'Riley Stone',
                address: '88 Harbor Lane, Lakeside, OH',
                home_phone: '555-202-1002',
                work_phone: '',
                relationship: 'Colleague',
            },
            {
                name: 'Sam Hale',
                address: '12 Oak Drive, Lakeside, OH',
                home_phone: '555-201-1099',
                work_phone: '',
                relationship: 'Personal reference',
            },
        ],
        work_histories: [
            {
                started_on: '2021-04-01',
                ended_on: '2024-02-28',
                job_title: 'Direct Support Professional',
                employer: 'Harbor Supports',
                employer_phone: '555-300-2211',
                employer_address: '400 Lake Road, Lakeside, OH',
                reason_for_leaving: 'Relocated closer to family.',
                job_duties: 'Supported daily living and community activities.',
            },
            {
                started_on: '2018-06-01',
                ended_on: '2021-03-15',
                job_title: 'Care assistant',
                employer: 'Northshore Day Program',
                employer_phone: '555-300-1188',
                employer_address: '19 Center Street, Lakeside, OH',
                reason_for_leaving: 'Accepted a DSP role.',
                job_duties: 'Assisted with meals and recreation.',
            },
        ],
        may_contact_current_employer: true,
        ohio_resident_5_years: true,
        residence_history: 'Lived in Lakeside, Ohio for the past 8 years.',
        used_other_names: false,
        other_names: '',
        ssn: '123-45-6789',
        alternate_ssn: '',
        has_conviction: false,
        incidents: [{ incident: '', city_state: '', charge: '' }],
        security_comments: '',
        tb_name: 'TB Screening',
        tb_expires_on: '2027-01-15',
        physician_name: 'Physician Good-Health Statement',
        physician_expires_on: '2027-01-15',
        create_login: true,
        user_id: '',
        password: 'Password123!',
        password_confirmation: 'Password123!',
        notes: 'Demo onboarding candidate for QA.',
        terminated_on: '',
    };
}

export function demoClientFill(supervisors: OptionItem[]): Record<string, string> {
    const stamp = Date.now().toString().slice(-5);

    return {
        first_name: 'Jordan',
        middle_name: 'Lee',
        last_name: 'Bennett',
        client_number: '',
        email: `jordan.bennett.${stamp}@example.com`,
        phone: '555-018-4402',
        date_of_birth: '1988-09-04',
        status: 'active',
        supervisor_id: supervisors[0] ? String(supervisors[0].id) : '',
        address_line_1: '55 Lakeview Drive',
        address_line_2: '',
        city: 'Lakeside',
        state: 'OH',
        postal_code: '44001',
        emergency_contact_name: 'Casey Bennett',
        emergency_contact_relationship: 'Sibling',
        emergency_contact_phone: '555-018-4411',
        notes: 'Prefers morning community outings and a consistent DSP.',
    };
}
